version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Asia/Tokyo"
    allow:
      - dependency-type: "all"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 10
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    groups:
      npm-all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/iac"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    groups:
      terraform-all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
    rebase-strategy: "auto"
    groups:
      github-all-dependencies:
        patterns:
          - "*"
